### ISSUE TITLE
A data racing bug

### ISSUE THREAD

**Issue by lgbo-ustc** [Kyligence/ClickHouse#242]
> You have to provide the following information whenever possible.

**Describe what's wrong**

In `StorageMergeTreeFactory`, the locks, `storage_map_mutex` and `metadata_map_mutex` seem to have invalid protection scope, and may cause coredump.

```
22/12/26 02:03:40 ERROR Executor: Exception in task 0.0 in stage 68.0 (TID 73)
java.lang.RuntimeException: unordered_map::at: key not found
0. std::logic_error::logic_error(char const*) @ 0x16a3ae94 in /tmp/libch.so
1. std::out_of_range::out_of_range(char const*) @ 0xa7fa769 in /tmp/libch.so
2. std::__1::__throw_out_of_range(char const*) @ 0xa7fa71f in /tmp/libch.so
3. local_engine::StorageMergeTreeFactory::getStorage(DB::StorageID, DB::ColumnsDescription, std::__1::function<std::__1::shared_ptr<local_engine::CustomStorageMergeTree> ()>) @ 0xa891c0a in /tmp/libch.so
4. local_engine::SerializedPlanParser::parseMergeTreeTable(substrait::ReadRel const&) @ 0xa81486d in /tmp/libch.so
5. local_engine::SerializedPlanParser::parseOp(substrait::Rel const&) @ 0xa81bcdb in /tmp/libch.so
6. local_engine::SerializedPlanParser::parse(std::__1::unique_ptr<substrait::Plan, std::__1::default_delete<substrait::Plan> >) @ 0xa81aa22 in /tmp/libch.so
7. local_engine::SerializedPlanParser::parse(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0xa824fb8 in /tmp/libch.so
8. Java_io_glutenproject_vectorized_ExpressionEvaluatorJniWrapper_nativeCreateKernelWithIterator @ 0xa8d3486 in /tmp/libch.so

	at io.glutenproject.vectorized.ExpressionEvaluatorJniWrapper.nativeCreateKernelWithIterator(Native Method)
	at io.glutenproject.vectorized.NativeExpressionEvaluator.createKernelWithBatchIterator(NativeExpressionEvaluator.java:57)
	at io.glutenproject.backendsapi.clickhouse.CHIteratorApi.genFirstStageIterator(CHIteratorApi.scala:171)
	at io.glutenproject.execution.GlutenWholeStageColumnarRDD.compute(GlutenWholeStageColumnarRDD.scala:113)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

> A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by lgbo-ustc** [comment]
https://github.com/Kyligence/ClickHouse/pull/243
