### ISSUE TITLE
Memory alloc fail when run `collect_list`

### ISSUE THREAD

**Issue by lgbo-ustc** [Kyligence/ClickHouse#382]
(you don't have to strictly follow this form)

**Describe the unexpected behaviour**
On the merging partial aggregated stage, memory alloc failed.
```
.
23/03/27 11:25:13 WARN scheduler.TaskSetManager: Lost task 0.2 in stage 21.0 (TID 2666) (executor 23): java.lang.RuntimeException: Allocator: Cannot mmap 128.00 TiB., errno: 12, strerror: Cannot allocate memory: While executing MergingAggregatedTransform
0. ./build1/../contrib/llvm-project/libcxx/include/exception:134: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int) @ 0x18fdaeda in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
1. ./build1/../src/Common/Exception.cpp:91: DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xe48e5f5 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
2. ./build1/../contrib/llvm-project/libcxx/include/string:1499: DB::ErrnoException::ErrnoException(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, int, std::__1::optional<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>> const&) @ 0xe4930f3 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
3. ./build1/../src/Common/Exception.cpp:0: DB::throwFromErrno(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, int, int) @ 0xe48f016 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
4. ./build1/../src/Common/Allocator.h:234: Allocator<false, false>::allocNoTrack(unsigned long, unsigned long) @ 0xe475a2d in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
5. ./build1/../src/Common/PODArray.h:136: void DB::PODArrayBase<8ul, 32ul, DB::MixedArenaAllocator<4096ul, Allocator<false, false>, DB::AlignedArenaAllocator<8ul>, 8ul>, 0ul, 0ul>::realloc<DB::Arena*&>(unsigned long, DB::Arena*&) @ 0xc424d58 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
6. ./build1/../src/Common/PODArray.h:0: void DB::PODArray<long, 32ul, DB::MixedArenaAllocator<4096ul, Allocator<false, false>, DB::AlignedArenaAllocator<8ul>, 8ul>, 0ul, 0ul>::insertByOffsets<DB::PODArray<long, 32ul, DB::MixedArenaAllocator<4096ul, Allocator<false, false>, DB::AlignedArenaAllocator<8ul>, 8ul>, 0ul, 0ul> const&, DB::Arena*&>(DB::PODArray<long, 32ul, DB::MixedArenaAllocator<4096ul, Allocator<false, false>, DB::AlignedArenaAllocator<8ul>, 8ul>, 0ul, 0ul> const&, unsigned long, unsigned long, DB::Arena*&) @ 0xc45040d in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
7. ./build1/../src/AggregateFunctions/AggregateFunctionGroupArray.h:201: DB::GroupArrayNumericImpl<long, DB::GroupArrayTrait<false, false, (DB::Sampler)0>>::merge(char*, char const*, DB::Arena*) const @ 0xc44f0b4 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
8. ./build1/../utils/local-engine/AggregateFunctions/AggregateFunctionPartialMerge.h:110: DB::IAggregateFunctionHelper<local_engine::AggregateFunctionPartialMerge>::mergeBatch(unsigned long, unsigned long, char**, unsigned long, char* const*, DB::Arena*) const @ 0xbf4c55e in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
9. ./build1/../src/Interpreters/Aggregator.cpp:2784: void DB::Aggregator::mergeStreamsImplCase<false, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, true, false, true>, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(DB::Arena*, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, true, false, true>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, char*, unsigned long, unsigned long, std::__1::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul> const*, std::__1::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul> const*>> const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, DB::Arena*) const @ 0x1459a960 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
10. ./build1/../src/Interpreters/Aggregator.cpp:2828: void DB::Aggregator::mergeStreamsImpl<DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, true, false, true>, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(DB::Arena*, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, true, false, true>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, char*, bool, unsigned long, unsigned long, std::__1::vector<DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul> const*, std::__1::allocator<DB::PODArray<char*, 4096ul, Allocator<false, false>, 63ul, 64ul> const*>> const&, std::__1::vector<DB::IColumn const*, std::__1::allocator<DB::IColumn const*>> const&, DB::Arena*) const @ 0x1452c4c6 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
11. ./build1/../src/Interpreters/Aggregator.cpp:2808: void DB::Aggregator::mergeStreamsImpl<DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, true, false, true>, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>>(DB::Block, DB::Arena*, DB::AggregationMethodKeysFixed<HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>, true, false, true>&, HashMapTable<wide::integer<128ul, unsigned int>, HashMapCell<wide::integer<128ul, unsigned int>, char*, UInt128HashCRC32, HashTableNoState>, UInt128HashCRC32, HashTableGrowerWithPrecalculation<8ul>, Allocator<true, true>>&, char*, bool, DB::Arena*) const @ 0x14549665 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
12. ./build1/../src/Interpreters/Aggregator.cpp:3070: DB::Aggregator::mergeBlocks(std::__1::map<int, std::__1::list<DB::Block, std::__1::allocator<DB::Block>>, std::__1::less<int>, std::__1::allocator<std::__1::pair<int const, std::__1::list<DB::Block, std::__1::allocator<DB::Block>>>>>, DB::AggregatedDataVariants&, unsigned long) @ 0x144c704f in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
13. ./build1/../src/Processors/Transforms/MergingAggregatedTransform.cpp:0: DB::MergingAggregatedTransform::generate() @ 0x15db2b09 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
14. ./build1/../contrib/llvm-project/libcxx/include/vector:951: DB::IAccumulatingTransform::work() @ 0x15bebd83 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
15. ./build1/../src/Processors/Executors/ExecutionThreadContext.cpp:0: DB::ExecutionThreadContext::executeTask() @ 0x15c08080 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
16. ./build1/../src/Processors/Executors/PipelineExecutor.cpp:229: DB::PipelineExecutor::executeStepImpl(unsigned long, std::__1::atomic<bool>*) @ 0x15bfe83b in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
17. ./build1/../contrib/llvm-project/libcxx/include/atomic:958: DB::PipelineExecutor::executeStep(std::__1::atomic<bool>*) @ 0x15bfe389 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
18. ./build1/../src/Processors/Executors/PullingPipelineExecutor.cpp:54: DB::PullingPipelineExecutor::pull(DB::Chunk&) @ 0x15c0baaa in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
19. ./build1/../src/Processors/Executors/PullingPipelineExecutor.cpp:0: DB::PullingPipelineExecutor::pull(DB::Block&) @ 0x15c0bc90 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
20. ./build1/../utils/local-engine/Parser/SerializedPlanParser.cpp:0: local_engine::LocalExecutor::hasNext() @ 0xbbc0db0 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so
21. ./build1/../utils/local-engine/local_engine_jni.cpp:277: Java_io_glutenproject_vectorized_BatchIterator_nativeHasNext @ 0xbf83337 in /data2/hadoop/yarn/local/usercache/root/filecache/3836/libch.so

	at io.glutenproject.vectorized.BatchIterator.nativeHasNext(Native Method)
	at io.glutenproject.vectorized.BatchIterator.hasNextInternal(BatchIterator.java:48)
	at io.glutenproject.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:36)
	at io.glutenproject.backendsapi.clickhouse.CHIteratorApi$$anon$3.hasNext(CHIteratorApi.scala:222)
	at io.glutenproject.vectorized.CloseableCHColumnBatchIterator.hasNext(CloseableCHColumnBatchIterator.scala:41)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:350)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1491)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**How to reproduce**

reproduce by the following query
```sql
select cc_call_center_id, collect_list(cc_call_center_sk) from call_center group by cc_call_center_id;
```

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

**Error message and/or stacktrace**

**Additional context**

**Comment by lgbo-ustc** [comment]
We will solve this

**Comment by lgbo-ustc** [comment]
It's a bug abount null type mismatch
