### ISSUE TITLE
Coredump when ut exit, seems related to resource release of BroadCastJoinBuilder 

### ISSUE THREAD

**Issue by taiyang-li** [Kyligence/ClickHouse#410]
mvn test -pl backends-clickhouse -Dtest=None -Dsuites=io.glutenproject.execution.GlutenClickHouseTPCHSuite -DfailIfNoTests=false  -Pbackends-clickhouse -Phadoop-2.7.4 -Pspark-3.2 -Dhadoop.version=2.8.5 -Dbuild_cpp=OFF -Dcpp_tests=OFF -Dbuild_arrow=OFF -Dbuild_protobuf=ON -Dbuild_jemalloc=ON  -Dspark.gluten.sql.columnar.backend.lib=ch

```
(gdb) bt 
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f198175a859 in __GI_abort () at abort.c:79
#2  0x00007f1980ae3f2f in os::abort(bool) [clone .cold] () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#3  0x00007f1981423683 in VMError::report_and_die() () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#4  0x00007f1981273f4e in JVM_handle_linux_signal () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#5  0x00007f19812670ac in signalHandler(int, siginfo_t*, void*) () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#6  <signal handler called>
#7  0x0000000000000000 in ?? ()
#8  0x00007f17d9bb1cd4 in DB::HashJoin::~HashJoin (this=0x7f17e00ddf48) at ./src/Interpreters/HashJoin.cpp:1762
#9  0x00007f17d0d4dca4 in std::__1::__shared_count::__release_shared[abi:v15000]() (this=0x7f17e00ddf30) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:174
#10 std::__1::__shared_weak_count::__release_shared[abi:v15000]() (this=0x7f17e00ddf30) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:215
#11 std::__1::shared_ptr<DB::HashJoin>::~shared_ptr[abi:v15000]() (this=0x7f17e00ddb48) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702
#12 local_engine::StorageJoinFromReadBuffer::~StorageJoinFromReadBuffer (this=0x7f17e00dd938) at ./utils/local-engine/Storages/StorageJoinFromReadBuffer.h:16
#13 0x00007f17d0caeef2 in std::__1::__shared_count::__release_shared[abi:v15000]() (this=0x7f17e00dd920) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:174
#14 std::__1::__shared_weak_count::__release_shared[abi:v15000]() (this=0x7f17e00dd920) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:215
#15 std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer>::~shared_ptr[abi:v15000]() (this=0x7f181085c888) at ./contrib/llvm-project/libcxx/include/__memory/shared_ptr.h:702
#16 std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >::~pair (this=0x7f181085c870)
    at ./contrib/llvm-project/libcxx/include/__utility/pair.h:40
#17 std::__1::__destroy_at[abi:v15000]<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >, 0>(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >*) (__loc=0x7f181085c870)
    at ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:63
#18 std::__1::destroy_at[abi:v15000]<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >, 0>(std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >*) (__loc=0x7f181085c870)
    at ./contrib/llvm-project/libcxx/include/__memory/construct_at.h:88
#19 std::__1::allocator_traits<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >, void*> > >::destroy[abi:v15000]<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >, void, void>(std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >, void*> >&, std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >*) (__p=0x7f181085c870)
    at ./contrib/llvm-project/libcxx/include/__memory/allocator_traits.h:317
#20 std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> > > >::__deallocate_node (this=0x7f17dfbb2eb8 <local_engine::BroadCastJoinBuilder::storage_join_map>, __np=0x7f181085c860)
    at ./contrib/llvm-project/libcxx/include/__hash_table:1532
#21 std::__1::__hash_table<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >, std::__1::__unordered_map_hasher<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::__unordered_map_equal<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, true>, std::__1::allocator<std::__1::__hash_value_type<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::shared_ptr<local_engine::StorageJoinFromReadBuffer> > > >::~__hash_table (this=0x7f17dfbb2eb8 <local_engine::BroadCastJoinBuilder::storage_join_map>) at ./contrib/llvm-project/libcxx/include/__hash_table:1473
#22 0x00007f198177ea27 in __run_exit_handlers (status=0, listp=0x7f1981920718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#23 0x00007f198177ebe0 in __GI_exit (status=<optimized out>) at exit.c:139
#24 0x00007f1980f88d5e in vm_direct_exit(int) () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#25 0x00007f198142acda in VM_Operation::evaluate() () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#26 0x00007f19814288f0 in VMThread::evaluate_operation(VM_Operation*) [clone .constprop.0] () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#27 0x00007f1981428ef4 in VMThread::loop() () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#28 0x00007f1981429202 in VMThread::run() () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#29 0x00007f19812690b0 in java_start(Thread*) () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#30 0x00007f19816f9609 in start_thread (arg=<optimized out>) at pthread_create.c:477
--Type <RET> for more, q to quit, c to continue without paging--
#31 0x00007f1981857293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by taiyang-li** [comment]
fixed by https://github.com/Kyligence/ClickHouse/pull/411
